app/utils/models.py
from typing import Optional
import sqlalchemy as sa
import sqlalchemy.orm as so
from app import db
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app import login
from sqlalchemy import ForeignKey, Table, Column
from sqlalchemy.orm import Mapped, mapped_column, relationship

@login.user_loader
def load_user(id):
    """ 
    Flask-Login callback function.
    Converts user id into a User object
        
    """
    return db.session.get(User, int(id))

tags_todos_table = Table(
    "tags_todos_table",
    db.Model.metadata,
    Column("todo_id", ForeignKey("todos.id", ondelete="CASCADE")),
    Column("tag_id", ForeignKey("tags.id", ondelete="CASCADE")),
)


class User(UserMixin, db.Model):
    __tablename__ = "users"
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    username: so.Mapped[str] = so.mapped_column(
        sa.String(64), index=True, unique=True)
    password_hash: so.Mapped[Optional[str]] = so.mapped_column(sa.String(256))
    todos: so.Mapped[list['Todo']] = so.relationship(back_populates='user')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def get_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"<User id={self.id} username='{self.username}'>"


class Todo(db.Model):
    __tablename__ = "todos"
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    title: so.Mapped[str] = so.mapped_column(sa.String(), index=True)
    description: so.Mapped[str] = so.mapped_column(sa.String())
    created_at: so.Mapped[datetime] = so.mapped_column(
        sa.DateTime, default=datetime.now)
    
    tags: Mapped[list["Tag"]] = relationship(
        secondary=tags_todos_table, back_populates='todos')
    
    user_id: so.Mapped[int] = so.mapped_column(
        sa.ForeignKey('users.id'), index=True, nullable=False)
    user: so.Mapped[User] = so.relationship(back_populates='todos')
    completed: so.Mapped[bool] = so.mapped_column(sa.Boolean, default=False)

    def __repr__(self):
        return f'<Todo id={self.id} title={self.title}>'
    

class Tag(db.Model):
    __tablename__ = "tags"
    id: so.Mapped[int] = so.mapped_column(sa.Integer, primary_key=True)
    content: so.Mapped[str] = mapped_column(sa.String(120), nullable=False)

    # link back to Todo
    todos: Mapped[list["Todo"]] = relationship(
        secondary=tags_todos_table, back_populates='tags')

    def __str__(self):
        return self.content

app/utils/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, EqualTo, ValidationError
from app import db
import sqlalchemy as sa
from app.utils.models import User

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(),
                              EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = db.session.scalar(sa.select(User).where(
            User.username == username.data))
        if user is not None:
            raise ValidationError('Please use a different username.')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    
    from app.index import bp as main_bp
    from app.auth import auth as auth_bp
    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp)
    return app

app/index/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.index import routes

app/index/routes.py
from app.index import bp
from app import db
from flask import render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from app.utils.models import Todo, Tag

@bp.route("/")
@login_required
def index():
    todo_count = Todo.query.count()
    return render_template("index.html", todo_count=todo_count)


@bp.route("/tasks")
@login_required
def all_tasks():
    todos = Todo.query.all()
    return render_template("tasks.html", todos=todos)

@bp.route("/task/<int:task_id>")
@login_required
def task(task_id):
    task = Todo.query.get_or_404(task_id)
    return render_template("task.html", task=task)

@bp.route("/edit-task/<int:task_id>", methods=["GET", "POST"])
@login_required
def edit_task(task_id):
    task = Todo.query.get_or_404(task_id)
    if request.method == "POST":
        title = request.form.get("title")
        description = request.form.get("description")
        tags_list = request.form.get("tags", "")
        tag_names = [t.strip() for t in tags_list.split(",") if t.strip()]

        new_tags = []
        for name in tag_names:
            tag = Tag.query.filter_by(content=name).first()
            if not tag:
                tag = Tag(content=name)
                db.session.add(tag)
            new_tags.append(tag)

        task.title = title
        task.description = description
        task.tags = new_tags
        
        db.session.commit()
        
        
        return redirect(url_for("main.task", task_id=task_id))

    return render_template("task_form.html", task=task)


@bp.route("/create-task", methods=["GET", "POST"])
@login_required
def create_task():
    if request.method == "POST":
        title = request.form.get("title")
        description = request.form.get("description")
        tags_list = request.form.get("tags", "")
        tags = [t.strip() for t in tags_list.split(",") if t.strip()]

        task = Todo(
            title=title,
            description=description,
            user=current_user,
        )

        db.session.add(task)

        for tag_name in tags:
            tag = Tag.query.filter_by(content=tag_name).first()
            if not tag:
                tag = Tag(content=tag_name)
                db.session.add(tag)
            task.tags.append(tag)

        db.session.commit()

        return redirect(url_for("main.task", task_id=task.id))

    return render_template("task_form.html", task=None)


@bp.route("/delete-task/<int:task_id>", methods=["Post"])
@login_required
def delete_task(task_id):
    task = Todo.query.get_or_404(task_id)
    db.session.delete(task)
    db.session.commit()
    return redirect(url_for("main.all_tasks"))

@bp.route("/task/<int:task_id>/toggle", methods=["POST"])
@login_required
def toggle_task_completion(task_id):
    task = db.session.get(Todo, task_id)
    task.completed = not task.completed
    db.session.commit()

    if task.completed:
        flash(f"Task {task.title} marked as completed.")
    else:
        flash(f"Task {task.title} reopened.")
    return redirect(url_for("main.all_tasks"))

app/routes.py
from flask import Blueprint
from flask import render_template

bp = Blueprint("main", __name__)


@bp.route("/")
def index():
    return render_template("index.html")

@bp.route("/")
def all_tasks():
    return "<h1>List of all tasks</h1>"

@bp.route("/task/<int:task_id>")
def task(task_id):
    return f"<h1>Task detail page for task {task_id}</h1>"


@bp.route("/new-task")
def create_task():
    return f"<h1>Placeholder for creating a new task"

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Todo List</title>
    <link href="../static/css/style.css" rel="stylesheet">    
</head>
<body>
  <nav>
    <h1>Todo List</h1>
    <ul>
      <li class="navlink"><a href="{{ url_for('main.index') }}">Home</a></li>
      {% if current_user.is_anonymous %}
      <li class="navlink"><a href="{{ url_for('auth.login') }}">Login</a></li>
      <li class="navlink"><a href="{{ url_for('auth.register') }}">Register</a></li>
      {% else %}      
      <li class="navlink"><a href="{{ url_for('main.all_tasks') }}">View Tasks</a></li>
      <li class="navlink"><a href="{{ url_for('main.create_task') }}">New Task</a></li>
      <li class="navlink"><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      {% endif %}
    </ul>
  </nav>
  <main>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    {% block main %}
    {% endblock %}
    <script src="{{ url_for('static', filename='scripts/tagging.js') }}"></script>
  </main>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block main %}
    <h2>You have {{ todo_count }} tasks.<h2>
    <h3><a href={{ url_for('main.all_tasks') }}>Click here</a>to view your todo list.</h3>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block main %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span style="color: red;">[{{error}}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/new_task.html
{% extends 'base.html' %}

{% block main %}
    <h1>Create a new task</h1>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block main %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32)}}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32)}}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/task.html
{% extends 'base.html' %}
{% block main %}
<h1>{{ task.title }}</h1>
<p>{{ task.description }}</p>
<p><small>Created at: {{ task.created_at}}</p>
<p>Tags: {{ task.tags | map(attribute='content') | join(', ') }}</p>

<div class="task-actions">
    <a href="{{ url_for('main.edit_task', task_id=task.id) }}" class="btn">Edit</a>
    <form method="post" action="{{ url_for('main.delete_task', task_id=task.id) }}">
        <button type="submit" class="btn">Delete</button>
    </form>
    <form method="post" action="{{ url_for('main.toggle_task_completion', task_id=task.id) }}">
        {% if task.completed %}
            <button type="submit" class="btn">Reopen Task</button>
        {% else %}
            <button type="submit" class="btn">Mark Complete</button>
        {% endif %}
    </form>
</div>
{% endblock %}

app/templates/task_form.html
{% extends 'base.html' %} {% block main %}

  <form method="post" action="{% if task %} {{
  url_for('main.edit_task', task_id=task.id) }} {% else %} {{ url_for('main.create_task') }} {% endif %}" >

  <label
    >Title
    <input name="title" value="{{task.title if task else '' }}" />
  </label>
  <br />
  <label
    >Description
    <textarea name="description">{{ task.description if task else '' }}</textarea>
  </label>
  <br />
<!--tag container -->
<div class="tag-container">
    <label>Tags</label>
    {% for tag in task.tags %}
        <span class="tag">
            {{ tag }} <button type="button">✖</button>
        </span>
    {% endfor %}
    <input type="text">
</div>
  <!-- hidden input to store all tags -->
  <input type="hidden" name="tags" id="hidden-tags">
  <br/>
  <button type="submit" class="btn">Save Changes</button>
  <a href="{{ url_for('main.all_tasks')}}" class="btn">Cancel</a>

</form>
{% endblock %}

app/templates/tasks.html
{% extends 'base.html' %}

{% block main %}
    <h1>Your Todo List</h1>
    <ul class="task-list">
        {% for todo in todos %}
        <li><a href="{{ url_for("main.task", task_id=todo.id) }}">{{ todo.title }}</a></li>
        {% else %}
        <li class="placeholder-task">You're all done! <b><a href={{ url_for("main.create_task") }}>Add more</a></b></li>
        {% endfor %}
    </ul>
{% endblock %}